set search_path to locadora;

INSERT INTO clientes (nome, sobrenome, telefone, email, senha, cpf) VALUES ('Alexandre', 'Kovaleski', '054996595252', 'alexandre@kovaleski.com', 'asdcafadsfq21', '12345678910');
INSERT INTO clientes (nome, sobrenome, telefone, email, senha, cpf) VALUES ('Guilherme', 'Emanuel Fernando Viana', '086999498804', 'guilherme@emanuel.com', 'asd1q231', '05466669229');
INSERT INTO clientes (nome, sobrenome, telefone, email, senha, cpf) VALUES ('Patrícia', 'Louise Sales', '054999997374', 'pati@louise.com', '124134', '39541733794');
INSERT INTO clientes (nome, sobrenome, telefone, email, senha, cpf) VALUES ('Mateus', 'Iago de Paula', '054997949596', 'mateus@iago.com', '1234red312', '03103203345');
INSERT INTO clientes (nome, sobrenome, telefone, email, senha, cpf) VALUES ('Hugo', 'Breno Manuel da Conceição', '055987654321', 'hugo@breno.com', '1234d3r', '12345678911');
INSERT INTO clientes (nome, sobrenome, telefone, email, senha, cpf) VALUES ('Filipe', 'Oliver Freitas', '087998989898', 'filipe@oliver.com', '1234df321f', '32165498711');
INSERT INTO clientes (nome, sobrenome, telefone, email, senha, cpf) VALUES ('Tereza', 'Luzia Laís Monteiro', '09933352745', 'tereza@luzia.com', '1234567890', '11111111111');

INSERT INTO atores (nome) VALUES ('Vin Diesel');
INSERT INTO atores (nome) VALUES ('Poul Walker');
INSERT INTO atores (nome) VALUES ('Michelle Rodriguez');
INSERT INTO atores (nome) VALUES ('Jordana Brewster');
INSERT INTO atores (nome) VALUES ('Tyrese Gibson');
INSERT INTO atores (nome) VALUES ('Jason Statham');
INSERT INTO atores (nome) VALUES ('Sung Kang');
INSERT INTO atores (nome) VALUES ('Ludacris');
INSERT INTO atores (nome) VALUES ('Gal Gadot');
INSERT INTO atores (nome) VALUES ('Lucas Black');
INSERT INTO atores (nome) VALUES ('John Ortiz');
INSERT INTO atores (nome) VALUES ('Laz Alonso');
INSERT INTO atores (nome) VALUES ('Dwayne Johnson');
INSERT INTO atores (nome) VALUES ('Elsa Pataky');
INSERT INTO atores (nome) VALUES ('Luke Evans');
INSERT INTO atores (nome) VALUES ('Gina Carano');
INSERT INTO atores (nome) VALUES ('John Cena');
INSERT INTO atores (nome) VALUES ('Jason Momoa');
INSERT INTO atores (nome) VALUES ('Nathalie Emmanuele');
INSERT INTO atores (nome) VALUES ('Charlize Theron');
INSERT INTO atores (nome) VALUES ('Kurt Russell');
INSERT INTO atores (nome) VALUES ('Helen Mirren');

INSERT INTO atores (nome) VALUES ('Daniel Radcliffe');
INSERT INTO atores (nome) VALUES ('Rupert Grint');
INSERT INTO atores (nome) VALUES ('Emma Watson');
INSERT INTO atores (nome) VALUES ('Robbie Coltrane');
INSERT INTO atores (nome) VALUES ('Richard Harris');
INSERT INTO atores (nome) VALUES ('Maggie Smith');
INSERT INTO atores (nome) VALUES ('Alan Rickman');
INSERT INTO atores (nome) VALUES ('Tom Felton');
INSERT INTO atores (nome) VALUES ('Kenneth Branagh');
INSERT INTO atores (nome) VALUES ('Jason Isaacs');
INSERT INTO atores (nome) VALUES ('Gary Oldman');
INSERT INTO atores (nome) VALUES ('David Thewlis');
INSERT INTO atores (nome) VALUES ('Ralph Fiennes');
INSERT INTO atores (nome) VALUES ('Michael Gambon');
INSERT INTO atores (nome) VALUES ('Brendan Gleeson');
INSERT INTO atores (nome) VALUES ('Robert Pattinson');
INSERT INTO atores (nome) VALUES ('Imelda Staunton');
INSERT INTO atores (nome) VALUES ('Ian Hart');
INSERT INTO atores (nome) VALUES ('Helena Bonham Carter');

INSERT INTO generos (genero) VALUES ('Ação');
INSERT INTO generos (genero) VALUES ('Aventura');
INSERT INTO generos (genero) VALUES ('Cinema de Arte');
INSERT INTO generos (genero) VALUES ('Chanchada');
INSERT INTO generos (genero) VALUES ('Comédia');
INSERT INTO generos (genero) VALUES ('Comédia de Ação');
INSERT INTO generos (genero) VALUES ('Comédia de Terror');
INSERT INTO generos (genero) VALUES ('Comédia Dramática');
INSERT INTO generos (genero) VALUES ('Comédia Romântica');
INSERT INTO generos (genero) VALUES ('Dança');
INSERT INTO generos (genero) VALUES ('Documentário');
INSERT INTO generos (genero) VALUES ('Docuficção');
INSERT INTO generos (genero) VALUES ('Drama');
INSERT INTO generos (genero) VALUES ('Espionagem');
INSERT INTO generos (genero) VALUES ('Faroeste');
INSERT INTO generos (genero) VALUES ('Fantasia');
INSERT INTO generos (genero) VALUES ('Fantasia Ciêntifica');
INSERT INTO generos (genero) VALUES ('Ficção Ciêntifica');
INSERT INTO generos (genero) VALUES ('Filmes com Truques');
INSERT INTO generos (genero) VALUES ('Filmes de Guerra');
INSERT INTO generos (genero) VALUES ('Mistério');
INSERT INTO generos (genero) VALUES ('Musical');
INSERT INTO generos (genero) VALUES ('Filme Policial');
INSERT INTO generos (genero) VALUES ('Romance');
INSERT INTO generos (genero) VALUES ('Terror');
INSERT INTO generos (genero) VALUES ('Thriller');
INSERT INTO generos (genero) VALUES ('Adulto');

INSERT INTO franquias (nome) VALUES ('Velozes e Furiosos');
INSERT INTO franquias (nome) VALUES ('Harry Potter');

INSERT INTO classificacao (tarja_classificacao, valor, horas_expiracao) VALUES ('Lançamentos', '10.00', '24');
INSERT INTO classificacao (tarja_classificacao, valor, horas_expiracao) VALUES ('Padrão', '5.00', '48');