set search_path to locadora;

INSERT INTO personagens (nome, id_ator) VALUES ('Dominic Toretto', '1');
INSERT INTO personagens (nome, id_ator) VALUES ('Brian O Conner', '2');
INSERT INTO personagens (nome, id_ator) VALUES ('Letty Ortiz', '3');
INSERT INTO personagens (nome, id_ator) VALUES ('Mia Toretto', '4');
INSERT INTO personagens (nome, id_ator) VALUES ('Roman Pearce', '5');
INSERT INTO personagens (nome, id_ator) VALUES ('Deckard Shaw', '6');
INSERT INTO personagens (nome, id_ator) VALUES ('Han Lue', '7');
INSERT INTO personagens (nome, id_ator) VALUES ('Tej Parker', '8');
INSERT INTO personagens (nome, id_ator) VALUES ('Gisele Yashar', '9');
INSERT INTO personagens (nome, id_ator) VALUES ('Sean Boswell', '10');
INSERT INTO personagens (nome, id_ator) VALUES ('Campos', '12');
INSERT INTO personagens (nome, id_ator) VALUES ('Fenix Rise', '13');
INSERT INTO personagens (nome, id_ator) VALUES ('Luke Hobbs', '14');
INSERT INTO personagens (nome, id_ator) VALUES ('Elena Neves', '15');
INSERT INTO personagens (nome, id_ator) VALUES ('Owen Shaw', '16');
INSERT INTO personagens (nome, id_ator) VALUES ('Riley Hicks', '17');
INSERT INTO personagens (nome, id_ator) VALUES ('Jakob Toretto', '18');
INSERT INTO personagens (nome, id_ator) VALUES ('Dante Reyes', '19');
INSERT INTO personagens (nome, id_ator) VALUES ('Ramsey', '20');
INSERT INTO personagens (nome, id_ator) VALUES ('Cipher', '21');
INSERT INTO personagens (nome, id_ator) VALUES ('Mr. Nobody', '22');
INSERT INTO personagens (nome, id_ator) VALUES ('Magdalene Shaw', '23');

INSERT INTO personagens (nome, id_ator) VALUES ('Harry Potter', '23');
INSERT INTO personagens (nome, id_ator) VALUES ('Ron Weasley', '24');
INSERT INTO personagens (nome, id_ator) VALUES ('Hermione Granger', '25');
INSERT INTO personagens (nome, id_ator) VALUES ('Rubeus Hagrid', '26');
INSERT INTO personagens (nome, id_ator) VALUES ('Albus Dumbledore', '27');
INSERT INTO personagens (nome, id_ator) VALUES ('Minerva McGonagall', '28');
INSERT INTO personagens (nome, id_ator) VALUES ('Severo Snape', '29');
INSERT INTO personagens (nome, id_ator) VALUES ('Drago Malfoy', '30');
INSERT INTO personagens (nome, id_ator) VALUES ('Gilderoy Lockhart', '31');
INSERT INTO personagens (nome, id_ator) VALUES ('Lucius Malfoy', '32');
INSERT INTO personagens (nome, id_ator) VALUES ('Sirius Black', '33');
INSERT INTO personagens (nome, id_ator) VALUES ('Remo Lupin', '34');
INSERT INTO personagens (nome, id_ator) VALUES ('Lord Voldemort', '35');
INSERT INTO personagens (nome, id_ator) VALUES ('Albus Dumbledore', '36');
INSERT INTO personagens (nome, id_ator) VALUES ('Alastor Moody', '37');
INSERT INTO personagens (nome, id_ator) VALUES ('Cedrico Diggory', '38');
INSERT INTO personagens (nome, id_ator) VALUES ('Dolores Umbridge', '39');
INSERT INTO personagens (nome, id_ator) VALUES ('Quirrell', '40');
INSERT INTO personagens (nome, id_ator) VALUES ('Bellatrix Lestrange', '41');

INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('1', '1', '1');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('2', '1', '2');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('3', '1', '4');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('4', '1', '3');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('1', '2', '1');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('2', '2', '2');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('5', '2', '5');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('8', '2', '6');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('10', '3', '8');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('7', '3', '7');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('1', '4', '1');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('2', '4', '2');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('3', '4', '4');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('4', '4', '3');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('9', '4', '9');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('7', '4', '7');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('12', '4', '11');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('13', '4', '10');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('1', '5', '1');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('2', '5', '2');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('4', '5', '3');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('14', '5', '12');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('15', '5', '13');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('5', '5', '5');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('6', '5', '16');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('9', '5', '9');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('7', '5', '7');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('1', '6', '1');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('4', '6', '3');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('2', '6', '2');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('3', '6', '4');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('5', '6', '5');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('14', '6', '12');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('8', '6', '6');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('9', '6', '9');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('7', '6', '7');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('16', '6', '14');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('17', '6', '15');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('1', '7', '1');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('2', '7', '2');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('3', '7', '4');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('4', '7', '3');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('5', '7', '5');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('6', '7', '16');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('8', '7', '6');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('20', '7', '17');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('22', '7', '19');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('15', '7', '13');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('14', '7', '12');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('1', '8', '1');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('3', '8', '4');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('14', '8', '12');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('15', '8', '13');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('6', '8', '16');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('5', '8', '5');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('8', '8', '6');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('20', '8', '17');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('21', '8', '18');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('22', '8', '19');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('14', '9', '12');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('6', '9', '16');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('1', '10', '1');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('3', '10', '4');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('5', '10', '5');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('8', '10', '6');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('20', '10', '17');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('4', '10', '3');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('7', '10', '7');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('23', '10', '21');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('18', '10', '20');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('21', '10', '18');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('1', '11', '1');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('3', '11', '4');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('4', '11', '3');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('5', '11', '5');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('8', '11', '6');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('18', '11', '20');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('19', '11', '22');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('20', '11', '17');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('7', '11', '7');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('21', '11', '18');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('23', '11', '21');

INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('23', '1', '23');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('24', '1', '24');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('25', '1', '25');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('26', '1', '26');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('27', '1', '27');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('28', '1', '28');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('29', '1', '29');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('30', '1', '30');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('32', '1', '32');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('35', '1', '35');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('40', '1', '40');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('23', '2', '23');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('24', '2', '24');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('25', '2', '25');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('26', '2', '26');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('27', '2', '27');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('28', '2', '28');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('29', '2', '29');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('30', '2', '30');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('31', '2', '31');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('32', '2', '32');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('23', '3', '23');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('24', '3', '24');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('25', '3', '25');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('26', '3', '26');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('28', '3', '28');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('29', '3', '29');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('30', '3', '30');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('33', '3', '33');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('34', '3', '34');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('36', '3', '36');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('23', '4', '23');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('24', '4', '24');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('25', '4', '25');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('26', '4', '26');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('28', '4', '28');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('29', '4', '29');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('30', '4', '30');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('35', '4', '35');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('36', '4', '36');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('37', '4', '37');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('38', '4', '38');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('23', '5', '23');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('24', '5', '24');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('25', '5', '25');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('26', '5', '26');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('28', '5', '28');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('29', '5', '29');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('30', '5', '30');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('33', '5', '33');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('35', '5', '35');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('36', '5', '36');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('39', '5', '39');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('23', '6', '23');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('24', '6', '24');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('25', '6', '25');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('26', '6', '26');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('28', '6', '28');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('29', '6', '29');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('30', '6', '30');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('35', '6', '35');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('36', '6', '36');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('23', '7', '23');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('24', '7', '24');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('25', '7', '25');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('26', '7', '26');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('28', '7', '28');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('29', '7', '29');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('30', '7', '30');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('35', '7', '35');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('41', '7', '41');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('23', '8', '23');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('24', '8', '24');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('25', '8', '25');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('26', '8', '26');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('28', '8', '28');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('29', '8', '29');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('30', '8', '30');
INSERT INTO atores_filmes (id_ator, id_filme, id_personagem) VALUES ('41', '8', '41');


INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('01/02/2023', '03/02/2023', '1', '1');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('12/01/2021', '14/01/2021', '2', '5');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('01/06/2022', '03/06/2022', '3', '8');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('31/07/2022', '01/08/2022', '4', '6');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('16/06/2023', '18/06/2023', '5', '3');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('19/04/2023', '21/04/2023', '6', '4');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('11/12/2023', '13/12/2023', '7', '3');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('14/11/2022', '16/11/2022', '3', '2');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('09/01/2023', '11/01/2023', '1', '9');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('01/02/2023', '02/02/2023', '5', '11');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('01/03/2023', '02/03/2023', '2', '11');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('01/12/2022', '02/12/2022', '4', '11');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('01/05/2023', '02/05/2023', '2', '11');

INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('01/02/2023', '03/02/2023', '2', '13');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('12/01/2021', '14/01/2021', '4', '19');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('01/06/2022', '03/06/2022', '1', '15');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('31/07/2022', '01/08/2022', '3', '17');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('16/06/2023', '18/06/2023', '5', '12');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('19/04/2023', '21/04/2023', '6', '14');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('11/12/2023', '13/12/2023', '7', '16');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('14/11/2022', '16/11/2022', '3', '18');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('09/01/2023', '11/01/2023', '2', '14');
INSERT INTO aluguel (data_aluguel, data_expiracao, id_cliente, id_filme) VALUES ('01/02/2023', '02/02/2023', '5', '17');